name: Node.js cmeGroup Scraper

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x] # Change to the Node.js version you need

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2 # You can use setup-node@v2 for setting up Node.js
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node res.js
